import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import ReduxProvider from "./components/ReduxProvide";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* start header */}
        <ReduxProvider>
          <Header />
        </ReduxProvider>
        {/* end header */}

        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
